/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-12-05 at 23:57:45 UTC 
 * Modify at your own risk.
 */

package co.edu.unal.isii.client.accountendpoint;

/**
 * Service definition for Accountendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AccountendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Accountendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the accountendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://traveling-to-myef.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "accountendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Accountendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Accountendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link GetAccount#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetAccount getAccount(java.lang.String id) throws java.io.IOException {
    GetAccount result = new GetAccount(id);
    initialize(result);
    return result;
  }

  public class GetAccount extends AccountendpointRequest<co.edu.unal.isii.client.accountendpoint.model.Account> {

    private static final String REST_PATH = "account/{id}";

    /**
     * Create a request for the method "getAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link GetAccount#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetAccount#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAccount(java.lang.String id) {
      super(Accountendpoint.this, "GET", REST_PATH, null, co.edu.unal.isii.client.accountendpoint.model.Account.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAccount setAlt(java.lang.String alt) {
      return (GetAccount) super.setAlt(alt);
    }

    @Override
    public GetAccount setFields(java.lang.String fields) {
      return (GetAccount) super.setFields(fields);
    }

    @Override
    public GetAccount setKey(java.lang.String key) {
      return (GetAccount) super.setKey(key);
    }

    @Override
    public GetAccount setOauthToken(java.lang.String oauthToken) {
      return (GetAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAccount setQuotaUser(java.lang.String quotaUser) {
      return (GetAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAccount setUserIp(java.lang.String userIp) {
      return (GetAccount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetAccount setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAccount set(String parameterName, Object value) {
      return (GetAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link InsertAccount#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link co.edu.unal.isii.client.accountendpoint.model.Account}
   * @return the request
   */
  public InsertAccount insertAccount(co.edu.unal.isii.client.accountendpoint.model.Account content) throws java.io.IOException {
    InsertAccount result = new InsertAccount(content);
    initialize(result);
    return result;
  }

  public class InsertAccount extends AccountendpointRequest<co.edu.unal.isii.client.accountendpoint.model.Account> {

    private static final String REST_PATH = "account";

    /**
     * Create a request for the method "insertAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link InsertAccount#execute()} method to invoke the remote
     * operation. <p> {@link InsertAccount#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link co.edu.unal.isii.client.accountendpoint.model.Account}
     * @since 1.13
     */
    protected InsertAccount(co.edu.unal.isii.client.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, co.edu.unal.isii.client.accountendpoint.model.Account.class);
    }

    @Override
    public InsertAccount setAlt(java.lang.String alt) {
      return (InsertAccount) super.setAlt(alt);
    }

    @Override
    public InsertAccount setFields(java.lang.String fields) {
      return (InsertAccount) super.setFields(fields);
    }

    @Override
    public InsertAccount setKey(java.lang.String key) {
      return (InsertAccount) super.setKey(key);
    }

    @Override
    public InsertAccount setOauthToken(java.lang.String oauthToken) {
      return (InsertAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAccount setQuotaUser(java.lang.String quotaUser) {
      return (InsertAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAccount setUserIp(java.lang.String userIp) {
      return (InsertAccount) super.setUserIp(userIp);
    }

    @Override
    public InsertAccount set(String parameterName, Object value) {
      return (InsertAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link ListAccount#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAccount listAccount() throws java.io.IOException {
    ListAccount result = new ListAccount();
    initialize(result);
    return result;
  }

  public class ListAccount extends AccountendpointRequest<co.edu.unal.isii.client.accountendpoint.model.CollectionResponseAccount> {

    private static final String REST_PATH = "account";

    /**
     * Create a request for the method "listAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link ListAccount#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListAccount#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAccount() {
      super(Accountendpoint.this, "GET", REST_PATH, null, co.edu.unal.isii.client.accountendpoint.model.CollectionResponseAccount.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAccount setAlt(java.lang.String alt) {
      return (ListAccount) super.setAlt(alt);
    }

    @Override
    public ListAccount setFields(java.lang.String fields) {
      return (ListAccount) super.setFields(fields);
    }

    @Override
    public ListAccount setKey(java.lang.String key) {
      return (ListAccount) super.setKey(key);
    }

    @Override
    public ListAccount setOauthToken(java.lang.String oauthToken) {
      return (ListAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAccount setQuotaUser(java.lang.String quotaUser) {
      return (ListAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAccount setUserIp(java.lang.String userIp) {
      return (ListAccount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAccount setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAccount setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAccount set(String parameterName, Object value) {
      return (ListAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAccount#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAccount removeAccount(java.lang.String id) throws java.io.IOException {
    RemoveAccount result = new RemoveAccount(id);
    initialize(result);
    return result;
  }

  public class RemoveAccount extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "account/{id}";

    /**
     * Create a request for the method "removeAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link RemoveAccount#execute()} method to invoke the remote
     * operation. <p> {@link RemoveAccount#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAccount(java.lang.String id) {
      super(Accountendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAccount setAlt(java.lang.String alt) {
      return (RemoveAccount) super.setAlt(alt);
    }

    @Override
    public RemoveAccount setFields(java.lang.String fields) {
      return (RemoveAccount) super.setFields(fields);
    }

    @Override
    public RemoveAccount setKey(java.lang.String key) {
      return (RemoveAccount) super.setKey(key);
    }

    @Override
    public RemoveAccount setOauthToken(java.lang.String oauthToken) {
      return (RemoveAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAccount setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAccount setUserIp(java.lang.String userIp) {
      return (RemoveAccount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveAccount setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAccount set(String parameterName, Object value) {
      return (RemoveAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAccount#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link co.edu.unal.isii.client.accountendpoint.model.Account}
   * @return the request
   */
  public UpdateAccount updateAccount(co.edu.unal.isii.client.accountendpoint.model.Account content) throws java.io.IOException {
    UpdateAccount result = new UpdateAccount(content);
    initialize(result);
    return result;
  }

  public class UpdateAccount extends AccountendpointRequest<co.edu.unal.isii.client.accountendpoint.model.Account> {

    private static final String REST_PATH = "account";

    /**
     * Create a request for the method "updateAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link UpdateAccount#execute()} method to invoke the remote
     * operation. <p> {@link UpdateAccount#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link co.edu.unal.isii.client.accountendpoint.model.Account}
     * @since 1.13
     */
    protected UpdateAccount(co.edu.unal.isii.client.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "PUT", REST_PATH, content, co.edu.unal.isii.client.accountendpoint.model.Account.class);
    }

    @Override
    public UpdateAccount setAlt(java.lang.String alt) {
      return (UpdateAccount) super.setAlt(alt);
    }

    @Override
    public UpdateAccount setFields(java.lang.String fields) {
      return (UpdateAccount) super.setFields(fields);
    }

    @Override
    public UpdateAccount setKey(java.lang.String key) {
      return (UpdateAccount) super.setKey(key);
    }

    @Override
    public UpdateAccount setOauthToken(java.lang.String oauthToken) {
      return (UpdateAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAccount setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAccount setUserIp(java.lang.String userIp) {
      return (UpdateAccount) super.setUserIp(userIp);
    }

    @Override
    public UpdateAccount set(String parameterName, Object value) {
      return (UpdateAccount) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Accountendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Accountendpoint}. */
    @Override
    public Accountendpoint build() {
      return new Accountendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AccountendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAccountendpointRequestInitializer(
        AccountendpointRequestInitializer accountendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(accountendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
